# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abou',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='abou',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
