# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20171001_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abou',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='abou',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
